import '../global/styles.css';

import { Inter } from 'next/font/google'
import SideBar from './componetsHome/SideBar';

//^ Compoents 


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GOOSE_RELOADED',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  	return (
    	<html lang="en">
			<body className={inter.className}>

				<div id="Layout-Home">

					<div className="side-bar-container">
						<SideBar/>
					</div>

					{children}

				</div>
      			

				
				
			</body>
    	</html>
  	)
}
