import './global/styles.css'; //& This is where all the SASS styles are imported from.

import { Inter } from 'next/font/google'

//^ Compoents 


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GOOSE_RELOADED',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  	return (
    	<html lang="en">
			<body className={inter.className}>
      			

				{children}
				
				
			</body>
    	</html>
  	)
}
